# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CShapermynew.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import Qt, QSize, QRect, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import (QSizePolicy, QWidget, QGridLayout, QTabWidget, QGridLayout, QVBoxLayout, QLabel,
                             QPushButton, QLineEdit, QComboBox, QProgressBar, QFrame, QHBoxLayout, QTableView,
                             QScrollBar, QAction, QMenu, QStatusBar, QTextEdit, QMenuBar)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Function = QTabWidget(self.centralwidget)
        self.Function.setLayoutDirection(Qt.LeftToRight)
        self.Function.setTabBarAutoHide(False)
        self.Function.setObjectName("Function")
        self.Preprocess = QWidget()
        self.Preprocess.setObjectName("Preprocess")
        self.verticalLayout_5 = QVBoxLayout(self.Preprocess)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Layout_Pre = QVBoxLayout()
        self.Layout_Pre.setObjectName("Layout_Pre")
        self.Layout_title_Pre = QVBoxLayout()
        self.Layout_title_Pre.setObjectName("Layout_title_Pre")
        self.label_title_Pre = QLabel(self.Preprocess)
        self.label_title_Pre.setMaximumSize(QSize(16777215, 50))
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title_Pre.setFont(font)
        self.label_title_Pre.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_title_Pre.setAlignment(Qt.AlignCenter)
        self.label_title_Pre.setObjectName("label_title_Pre")
        self.Layout_title_Pre.addWidget(self.label_title_Pre)
        self.Layout_Pre.addLayout(self.Layout_title_Pre)
        self.Layout_params_Pre = QGridLayout()
        self.Layout_params_Pre.setObjectName("Layout_params_Pre")
        self.label_projectFolder_Pre = QLabel(self.Preprocess)
        self.label_projectFolder_Pre.setObjectName("label_projectFolder_Pre")
        self.Layout_params_Pre.addWidget(self.label_projectFolder_Pre, 7, 0, 1, 1)
        self.label_rawFolder_Pre = QLabel(self.Preprocess)
        self.label_rawFolder_Pre.setObjectName("label_rawFolder_Pre")
        self.Layout_params_Pre.addWidget(self.label_rawFolder_Pre, 0, 0, 1, 1)
        self.label_zReso_Pre = QLabel(self.Preprocess)
        self.label_zReso_Pre.setObjectName("label_zReso_Pre")
        self.Layout_params_Pre.addWidget(self.label_zReso_Pre, 3, 0, 1, 1)
        self.Btn_numberDict = QPushButton(self.Preprocess)
        self.Btn_numberDict.setObjectName("Btn_numberDict")
        self.Layout_params_Pre.addWidget(self.Btn_numberDict, 9, 2, 1, 1)
        self.Btn_rawFolder = QPushButton(self.Preprocess)
        self.Btn_rawFolder.setObjectName("Btn_rawFolder")
        self.Layout_params_Pre.addWidget(self.Btn_rawFolder, 0, 2, 1, 1)
        self.LE_zResolution = QLineEdit(self.Preprocess)
        self.LE_zResolution.setObjectName("LE_zResolution")
        self.Layout_params_Pre.addWidget(self.LE_zResolution, 3, 1, 1, 1)
        self.Btn_projectFolder = QPushButton(self.Preprocess)
        self.Btn_projectFolder.setObjectName("Btn_projectFolder")
        self.Layout_params_Pre.addWidget(self.Btn_projectFolder, 7, 2, 1, 1)
        self.CB_embryoNames = QComboBox(self.Preprocess)
        self.CB_embryoNames.setObjectName("CB_embryoNames")
        self.Layout_params_Pre.addWidget(self.CB_embryoNames, 1, 1, 1, 1)
        self.label_reduceRatio_Pre = QLabel(self.Preprocess)
        self.label_reduceRatio_Pre.setObjectName("label_reduceRatio_Pre")
        self.Layout_params_Pre.addWidget(self.label_reduceRatio_Pre, 4, 0, 1, 1)
        self.LE_sliceNum = QLineEdit(self.Preprocess)
        self.LE_sliceNum.setObjectName("LE_sliceNum")
        self.Layout_params_Pre.addWidget(self.LE_sliceNum, 5, 1, 1, 1)
        self.label_sliceNum_Pre = QLabel(self.Preprocess)
        self.label_sliceNum_Pre.setObjectName("label_sliceNum_Pre")
        self.Layout_params_Pre.addWidget(self.label_sliceNum_Pre, 5, 0, 1, 1)
        self.Btn_lineageFile = QPushButton(self.Preprocess)
        self.Btn_lineageFile.setObjectName("Btn_lineageFile")
        self.Layout_params_Pre.addWidget(self.Btn_lineageFile, 8, 2, 1, 1)
        self.label_xyum_Pre = QLabel(self.Preprocess)
        self.label_xyum_Pre.setObjectName("label_xyum_Pre")
        self.Layout_params_Pre.addWidget(self.label_xyum_Pre, 2, 2, 1, 1)
        self.LE_lineage = QLineEdit(self.Preprocess)
        self.LE_lineage.setObjectName("LE_lineage")
        self.Layout_params_Pre.addWidget(self.LE_lineage, 8, 1, 1, 1)
        self.label_maxTime_Pre = QLabel(self.Preprocess)
        self.label_maxTime_Pre.setObjectName("label_maxTime_Pre")
        self.Layout_params_Pre.addWidget(self.label_maxTime_Pre, 6, 0, 1, 1)
        self.label_numberDict_Pre = QLabel(self.Preprocess)
        self.label_numberDict_Pre.setObjectName("label_numberDict_Pre")
        self.Layout_params_Pre.addWidget(self.label_numberDict_Pre, 9, 0, 1, 1)
        self.LE_reduceRatio = QLineEdit(self.Preprocess)
        self.LE_reduceRatio.setObjectName("LE_reduceRatio")
        self.Layout_params_Pre.addWidget(self.LE_reduceRatio, 4, 1, 1, 1)
        self.label_embryoName_Pre = QLabel(self.Preprocess)
        self.label_embryoName_Pre.setObjectName("label_embryoName_Pre")
        self.Layout_params_Pre.addWidget(self.label_embryoName_Pre, 1, 0, 1, 1)
        self.LE_rawFolder = QLineEdit(self.Preprocess)
        self.LE_rawFolder.setObjectName("LE_rawFolder")
        self.Layout_params_Pre.addWidget(self.LE_rawFolder, 0, 1, 1, 1)
        self.LE_maxTime = QLineEdit(self.Preprocess)
        self.LE_maxTime.setObjectName("LE_maxTime")
        self.Layout_params_Pre.addWidget(self.LE_maxTime, 6, 1, 1, 1)
        self.label_lineageFile_Pre = QLabel(self.Preprocess)
        self.label_lineageFile_Pre.setObjectName("label_lineageFile_Pre")
        self.Layout_params_Pre.addWidget(self.label_lineageFile_Pre, 8, 0, 1, 1)
        self.LE_xyResolution = QLineEdit(self.Preprocess)
        self.LE_xyResolution.setObjectName("LE_xyResolution")
        self.Layout_params_Pre.addWidget(self.LE_xyResolution, 2, 1, 1, 1)
        self.LE_projectFolder = QLineEdit(self.Preprocess)
        self.LE_projectFolder.setObjectName("LE_projectFolder")
        self.Layout_params_Pre.addWidget(self.LE_projectFolder, 7, 1, 1, 1)
        self.label_zum_Pre = QLabel(self.Preprocess)
        self.label_zum_Pre.setObjectName("label_zum_Pre")
        self.Layout_params_Pre.addWidget(self.label_zum_Pre, 3, 2, 1, 1)
        self.Btn_runPreprocess = QPushButton(self.Preprocess)
        self.Btn_runPreprocess.setObjectName("Btn_runPreprocess")
        self.Layout_params_Pre.addWidget(self.Btn_runPreprocess, 4, 3, 1, 1)
        self.label_xyReso_Pre = QLabel(self.Preprocess)
        self.label_xyReso_Pre.setObjectName("label_xyReso_Pre")
        self.Layout_params_Pre.addWidget(self.label_xyReso_Pre, 2, 0, 1, 1)
        self.Btn_stopPreprocess = QPushButton(self.Preprocess)
        self.Btn_stopPreprocess.setObjectName("Btn_stopPreprocess")
        self.Layout_params_Pre.addWidget(self.Btn_stopPreprocess, 5, 3, 1, 1)
        self.LE_numberDict = QLineEdit(self.Preprocess)
        self.LE_numberDict.setObjectName("LE_numberDict")
        self.Layout_params_Pre.addWidget(self.LE_numberDict, 9, 1, 1, 1)
        self.label_unusedfirst_2 = QLabel(self.Preprocess)
        self.label_unusedfirst_2.setText("")
        self.label_unusedfirst_2.setObjectName("label_unusedfirst_2")
        self.Layout_params_Pre.addWidget(self.label_unusedfirst_2, 10, 0, 1, 1)
        self.Layout_Pre.addLayout(self.Layout_params_Pre)
        self.Layout_progress_Pre = QHBoxLayout()
        self.Layout_progress_Pre.setObjectName("Layout_progress_Pre")
        self.progressPreprocess = QLabel(self.Preprocess)
        self.progressPreprocess.setText("")
        self.progressPreprocess.setObjectName("progressPreprocess")
        self.Layout_progress_Pre.addWidget(self.progressPreprocess)
        self.PreprogressBar = QProgressBar(self.Preprocess)
        self.PreprogressBar.setMaximumSize(QSize(250, 16777215))
        self.PreprogressBar.setProperty("value", 0)
        self.PreprogressBar.setObjectName("PreprogressBar")
        self.Layout_progress_Pre.addWidget(self.PreprogressBar)
        self.Layout_Pre.addLayout(self.Layout_progress_Pre)
        self.verticalLayout_5.addLayout(self.Layout_Pre)
        self.Function.addTab(self.Preprocess, "")

        # ==== segmentation part
        self.Segmentation = QWidget()
        self.Segmentation.setObjectName("Segmentation")
        self.verticalLayout_8 = QVBoxLayout(self.Segmentation)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Layout_Seg = QVBoxLayout()
        self.Layout_Seg.setObjectName("Layout_Seg")
        self.Layout_title_Seg = QVBoxLayout()
        self.Layout_title_Seg.setObjectName("Layout_title_Seg")
        self.label_title_Seg = QLabel(self.Segmentation)
        self.label_title_Seg.setMaximumSize(QSize(16777215, 50))
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title_Seg.setFont(font)
        self.label_title_Seg.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_title_Seg.setAlignment(Qt.AlignCenter)
        self.label_title_Seg.setObjectName("label_title_Seg")
        self.Layout_title_Seg.addWidget(self.label_title_Seg)
        self.Layout_Seg.addLayout(self.Layout_title_Seg)
        self.Layout_params_Seg = QGridLayout()
        self.Layout_params_Seg.setObjectName("Layout_params_Seg")

        # self.CB_model_list = QComboBox(self.Segmentation)
        # self.CB_model_list.setObjectName("CB_model_Seg")
        # self.CB_model_list.addItem("")
        # self.CB_model_list.addItem("")
        # self.CB_model_list.addItem("")
        # self.Layout_params_Seg.addWidget(self.CB_model_list, 5, 1, 1, 1)

        self.label_projectFolder_Seg = QLabel(self.Segmentation)
        self.label_projectFolder_Seg.setObjectName("label_projectFolder_Seg")
        self.Layout_params_Seg.addWidget(self.label_projectFolder_Seg, 0, 0, 1, 1)
        self.LE_projectFolder_Seg = QLineEdit(self.Segmentation)
        self.LE_projectFolder_Seg.setObjectName("LE_projectFolder_Seg")
        self.Layout_params_Seg.addWidget(self.LE_projectFolder_Seg, 0, 1, 1, 1)
        self.Btn_projectFolder_Seg = QPushButton(self.Segmentation)
        self.Btn_projectFolder_Seg.setObjectName("Btn_projectFolder_Seg")
        self.Layout_params_Seg.addWidget(self.Btn_projectFolder_Seg, 0, 2, 1, 1)

        self.label_embryoName_Seg = QLabel(self.Segmentation)
        self.label_embryoName_Seg.setObjectName("label_embryoName_Seg")
        self.Layout_params_Seg.addWidget(self.label_embryoName_Seg, 1, 0, 1, 1)
        self.CB_embryoNames_Seg = QComboBox(self.Segmentation)
        self.CB_embryoNames_Seg.setObjectName("CB_embryoNames_Seg")
        self.Layout_params_Seg.addWidget(self.CB_embryoNames_Seg, 1, 1, 1, 1)

        self.label_maxTime_Seg = QLabel(self.Segmentation)
        self.label_maxTime_Seg.setObjectName("label_maxTime_Seg")
        self.Layout_params_Seg.addWidget(self.label_maxTime_Seg, 2, 0, 1, 1)
        self.LE_maxTime_Seg = QLineEdit(self.Segmentation)
        self.LE_maxTime_Seg.setObjectName("LE_maxTime_Seg")
        self.Layout_params_Seg.addWidget(self.LE_maxTime_Seg, 2, 1, 1, 1)

        self.label_batchSize_Seg = QLabel(self.Segmentation)
        self.label_batchSize_Seg.setObjectName("label_batchSize_Seg")
        self.Layout_params_Seg.addWidget(self.label_batchSize_Seg, 3, 0, 1, 1)
        self.LE_batchSize_Seg = QLineEdit(self.Segmentation)
        self.LE_batchSize_Seg.setObjectName("LE_batchSize_Seg")
        self.Layout_params_Seg.addWidget(self.LE_batchSize_Seg, 3, 1, 1, 1)

        self.label_lineage_Seg = QLabel(self.Segmentation)
        self.label_lineage_Seg.setFrameShape(QFrame.NoFrame)
        self.label_lineage_Seg.setObjectName("label_lineage_Seg")
        self.Layout_params_Seg.addWidget(self.label_lineage_Seg, 4, 0, 1, 1)
        self.CB_lineage_Seg = QComboBox(self.Segmentation)
        self.CB_lineage_Seg.setObjectName("CB_lineage_Seg")
        self.CB_lineage_Seg.addItem("")
        self.CB_lineage_Seg.addItem("")
        self.CB_lineage_Seg.addItem("")
        self.Layout_params_Seg.addWidget(self.CB_lineage_Seg, 4, 1, 1, 1)
        self.Btn_runSegmentation = QPushButton(self.Segmentation)
        self.Btn_runSegmentation.setObjectName("Btn_runSegmentation")
        self.Layout_params_Seg.addWidget(self.Btn_runSegmentation, 4, 3, 1, 1)

        self.label_model_tag = QLabel(self.Segmentation)
        self.label_model_tag.setFrameShape(QFrame.NoFrame)
        self.label_model_tag.setObjectName("label_model_tag")
        self.Layout_params_Seg.addWidget(self.label_model_tag, 5, 0, 1, 1)
        self.model_lists = QComboBox(self.Segmentation)
        self.model_lists.setObjectName("CB_model_list")
        self.model_lists.addItem("")
        self.model_lists.addItem("")
        self.Layout_params_Seg.addWidget(self.model_lists, 5, 1, 1, 1)
        self.Btn_stopSegmentation = QPushButton(self.Segmentation)
        self.Btn_stopSegmentation.setObjectName("Btn_stopSegmentation")
        self.Layout_params_Seg.addWidget(self.Btn_stopSegmentation, 5, 3, 1, 1)

        self.label_modelFile_Seg = QLabel(self.Segmentation)
        self.label_modelFile_Seg.setObjectName("label_modelFile_Seg")
        self.Layout_params_Seg.addWidget(self.label_modelFile_Seg, 6, 0, 1, 1)
        self.LE_modelFile_Seg = QLineEdit(self.Segmentation)
        self.LE_modelFile_Seg.setObjectName("LE_modelFile_Seg")
        self.Layout_params_Seg.addWidget(self.LE_modelFile_Seg, 6, 1, 1, 1)
        self.Btn_modelFile_Seg = QPushButton(self.Segmentation)
        self.Btn_modelFile_Seg.setObjectName("Btn_modelFile_Seg")
        self.Layout_params_Seg.addWidget(self.Btn_modelFile_Seg, 6, 2, 1, 1)

        self.label_unusedsecond = QLabel(self.Segmentation)
        self.label_unusedsecond.setText("")
        self.label_unusedsecond.setObjectName("label_unusedsecond")
        self.Layout_params_Seg.addWidget(self.label_unusedsecond, 7, 0, 1, 1)

        self.label_unusedthird = QLabel(self.Segmentation)
        self.label_unusedthird.setText("")
        self.label_unusedthird.setObjectName("label_unusedthird")
        self.Layout_params_Seg.addWidget(self.label_unusedthird, 8, 0, 1, 1)


        self.label_unusedforth = QLabel(self.Segmentation)
        self.label_unusedforth.setText("")
        self.label_unusedforth.setObjectName("label_unusedforth")
        self.Layout_params_Seg.addWidget(self.label_unusedforth, 9, 0, 1, 1)

        self.label_unusedfifth = QLabel(self.Segmentation)
        self.label_unusedfifth.setText("")
        self.label_unusedfifth.setObjectName("label_unusedfifth")
        self.Layout_params_Seg.addWidget(self.label_unusedfifth, 10, 0, 1, 1)

        self.Layout_Seg.addLayout(self.Layout_params_Seg)
        self.Layout_progress_Seg = QHBoxLayout()
        self.Layout_progress_Seg.setObjectName("Layout_progress_Seg")
        self.progressSegmentation = QLabel(self.Segmentation)
        self.progressSegmentation.setText("")
        self.progressSegmentation.setObjectName("progressSegmentation")
        self.Layout_progress_Seg.addWidget(self.progressSegmentation)
        self.SegmentationBar = QProgressBar(self.Segmentation)
        self.SegmentationBar.setMaximumSize(QSize(250, 16777215))
        self.SegmentationBar.setProperty("value", 0)
        self.SegmentationBar.setObjectName("SegmentationBar")
        self.Layout_progress_Seg.addWidget(self.SegmentationBar)
        self.Layout_Seg.addLayout(self.Layout_progress_Seg)
        self.verticalLayout_8.addLayout(self.Layout_Seg)
        self.Function.addTab(self.Segmentation, "")

        # ======= Analysis part
        self.Analysis = QWidget()
        self.Analysis.setObjectName("Analysis")
        self.verticalLayout_11 = QVBoxLayout(self.Analysis)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Layout_Ana = QVBoxLayout()
        self.Layout_Ana.setObjectName("Layout_Ana")
        self.Layout_title_Ana = QVBoxLayout()
        self.Layout_title_Ana.setObjectName("Layout_title_Ana")
        self.label_title_Ana = QLabel(self.Analysis)
        self.label_title_Ana.setMaximumSize(QSize(16777215, 50))
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title_Ana.setFont(font)
        self.label_title_Ana.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_title_Ana.setAlignment(Qt.AlignCenter)
        self.label_title_Ana.setObjectName("label_title_Ana")
        self.Layout_title_Ana.addWidget(self.label_title_Ana)
        self.Layout_Ana.addLayout(self.Layout_title_Ana)
        self.Layout_params_Ana = QGridLayout()
        self.Layout_params_Ana.setObjectName("Layout_params_Ana")
        self.Btn_lineageFile_Ana = QPushButton(self.Analysis)
        self.Btn_lineageFile_Ana.setObjectName("Btn_lineageFile_Ana")
        self.Layout_params_Ana.addWidget(self.Btn_lineageFile_Ana, 6, 2, 1, 1)
        self.Btn_stopAnalysis = QPushButton(self.Analysis)
        self.Btn_stopAnalysis.setObjectName("Btn_stopAnalysis")
        self.Layout_params_Ana.addWidget(self.Btn_stopAnalysis, 3, 3, 1, 1)
        self.Btn_rawFolder_Ana = QPushButton(self.Analysis)
        self.Btn_rawFolder_Ana.setObjectName("Btn_rawFolder_Ana")
        self.Layout_params_Ana.addWidget(self.Btn_rawFolder_Ana, 3, 2, 1, 1)
        self.label_rawFolder_Ana = QLabel(self.Analysis)
        self.label_rawFolder_Ana.setObjectName("label_rawFolder_Ana")
        self.Layout_params_Ana.addWidget(self.label_rawFolder_Ana, 3, 0, 1, 1)
        self.Btn_numberDict_Ana = QPushButton(self.Analysis)
        self.Btn_numberDict_Ana.setObjectName("Btn_numberDict_Ana")
        self.Layout_params_Ana.addWidget(self.Btn_numberDict_Ana, 2, 2, 1, 1)
        self.LE_rawFolder_Ana = QLineEdit(self.Analysis)
        self.LE_rawFolder_Ana.setObjectName("LE_rawFolder_Ana")
        self.Layout_params_Ana.addWidget(self.LE_rawFolder_Ana, 3, 1, 1, 1)
        # self.Btn_runAll = QPushButton(self.Analysis)
        # self.Btn_runAll.setStyleSheet("background-color: rgb(255, 170, 0);")
        # self.Btn_runAll.setObjectName("Btn_runAll")
        # self.Layout_params_Ana.addWidget(self.Btn_runAll, 4, 3, 1, 1)
        self.LE_projectFolder_Ana = QLineEdit(self.Analysis)
        self.LE_projectFolder_Ana.setObjectName("LE_projectFolder_Ana")
        self.Layout_params_Ana.addWidget(self.LE_projectFolder_Ana, 5, 1, 1, 1)
        self.label_numberDict_Ana = QLabel(self.Analysis)
        self.label_numberDict_Ana.setObjectName("label_numberDict_Ana")
        self.Layout_params_Ana.addWidget(self.label_numberDict_Ana, 2, 0, 1, 1)
        self.label_sliceNum_Ana = QLabel(self.Analysis)
        self.label_sliceNum_Ana.setObjectName("label_sliceNum_Ana")
        self.Layout_params_Ana.addWidget(self.label_sliceNum_Ana, 0, 0, 1, 1)
        self.LE_lineage_Ana = QLineEdit(self.Analysis)
        self.LE_lineage_Ana.setObjectName("LE_lineage_Ana")
        self.Layout_params_Ana.addWidget(self.LE_lineage_Ana, 6, 1, 1, 1)
        self.label_lineageFile_Ana = QLabel(self.Analysis)
        self.label_lineageFile_Ana.setObjectName("label_lineageFile_Ana")
        self.Layout_params_Ana.addWidget(self.label_lineageFile_Ana, 6, 0, 1, 1)
        self.label_unusedfirst_Ana = QLabel(self.Analysis)
        self.label_unusedfirst_Ana.setText("")
        self.label_unusedfirst_Ana.setObjectName("label_unusedfirst_Ana")
        self.Layout_params_Ana.addWidget(self.label_unusedfirst_Ana, 7, 0, 1, 1)
        self.label_unusedthird_Ana = QLabel(self.Analysis)
        self.label_unusedthird_Ana.setText("")
        self.label_unusedthird_Ana.setObjectName("label_unusedthird_Ana")
        self.Layout_params_Ana.addWidget(self.label_unusedthird_Ana, 9, 0, 1, 1)
        self.LE_sliceNum_Ana = QLineEdit(self.Analysis)
        self.LE_sliceNum_Ana.setObjectName("LE_sliceNum_Ana")
        self.Layout_params_Ana.addWidget(self.LE_sliceNum_Ana, 0, 1, 1, 1)
        self.LE_numberDict_Ana = QLineEdit(self.Analysis)
        self.LE_numberDict_Ana.setObjectName("LE_numberDict_Ana")
        self.Layout_params_Ana.addWidget(self.LE_numberDict_Ana, 2, 1, 1, 1)
        self.label_projectFolder_Ana = QLabel(self.Analysis)
        self.label_projectFolder_Ana.setObjectName("label_projectFolder_Ana")
        self.Layout_params_Ana.addWidget(self.label_projectFolder_Ana, 5, 0, 1, 1)
        self.label_embryoName_Ana = QLabel(self.Analysis)
        self.label_embryoName_Ana.setObjectName("label_embryoName_Ana")
        self.Layout_params_Ana.addWidget(self.label_embryoName_Ana, 4, 0, 1, 1)
        self.LE_xyResolution_Ana = QLineEdit(self.Analysis)
        self.LE_xyResolution_Ana.setObjectName("LE_xyResolution_Ana")
        self.Layout_params_Ana.addWidget(self.LE_xyResolution_Ana, 1, 1, 1, 1)
        self.label_unusedsecond_Ana = QLabel(self.Analysis)
        self.label_unusedsecond_Ana.setText("")
        self.label_unusedsecond_Ana.setObjectName("label_unusedsecond_Ana")
        self.Layout_params_Ana.addWidget(self.label_unusedsecond_Ana, 8, 0, 1, 1)
        self.CB_embryoNames_Ana = QComboBox(self.Analysis)
        self.CB_embryoNames_Ana.setObjectName("CB_embryoNames_Ana")
        self.Layout_params_Ana.addWidget(self.CB_embryoNames_Ana, 4, 1, 1, 1)
        self.Btn_runAnalysis = QPushButton(self.Analysis)
        self.Btn_runAnalysis.setObjectName("Btn_runAnalysis")
        self.Layout_params_Ana.addWidget(self.Btn_runAnalysis, 2, 3, 1, 1)
        self.label_xyReso_Ana = QLabel(self.Analysis)
        self.label_xyReso_Ana.setObjectName("label_xyReso_Ana")
        self.Layout_params_Ana.addWidget(self.label_xyReso_Ana, 1, 0, 1, 1)
        self.Btn_projectFolder_Ana = QPushButton(self.Analysis)
        self.Btn_projectFolder_Ana.setObjectName("Btn_projectFolder_Ana")
        self.Layout_params_Ana.addWidget(self.Btn_projectFolder_Ana, 5, 2, 1, 1)
        self.label_unusedforth_Ana = QLabel(self.Analysis)
        self.label_unusedforth_Ana.setText("")
        self.label_unusedforth_Ana.setObjectName("label_unusedforth_Ana")
        self.Layout_params_Ana.addWidget(self.label_unusedforth_Ana, 10, 0, 1, 1)
        self.Layout_Ana.addLayout(self.Layout_params_Ana)
        self.Layout_progress_Ana = QHBoxLayout()
        self.Layout_progress_Ana.setObjectName("Layout_progress_Ana")
        self.progressAnalysis = QLabel(self.Analysis)
        self.progressAnalysis.setText("")
        self.progressAnalysis.setObjectName("progressAnalysis")
        self.Layout_progress_Ana.addWidget(self.progressAnalysis)
        self.AnalysisBar = QProgressBar(self.Analysis)
        self.AnalysisBar.setMaximumSize(QSize(250, 16777215))
        self.AnalysisBar.setProperty("value", 0)
        self.AnalysisBar.setObjectName("AnalysisBar")
        self.Layout_progress_Ana.addWidget(self.AnalysisBar)
        self.Layout_Ana.addLayout(self.Layout_progress_Ana)
        self.verticalLayout_11.addLayout(self.Layout_Ana)
        self.Function.addTab(self.Analysis, "")
        self.Result = QWidget()
        self.Result.setObjectName("Result")
        self.verticalLayout_13 = QVBoxLayout(self.Result)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Layout_Result = QVBoxLayout()
        self.Layout_Result.setObjectName("Layout_Result")
        self.label_title_Res = QLabel(self.Result)
        self.label_title_Res.setMaximumSize(QSize(16777215, 50))
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title_Res.setFont(font)
        self.label_title_Res.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_title_Res.setAlignment(Qt.AlignCenter)
        self.label_title_Res.setObjectName("label_title_Res")
        self.Layout_Result.addWidget(self.label_title_Res)
        self.tabWidget_Res = QTabWidget(self.Result)
        self.tabWidget_Res.setObjectName("tabWidget_Res")
        self.tab_Surface = QWidget()
        self.tab_Surface.setObjectName("tab_Surface")
        self.verticalLayout_15 = QVBoxLayout(self.tab_Surface)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableView_Surface = QTableView(self.tab_Surface)
        self.tableView_Surface.setObjectName("tableView_Surface")
        self.verticalLayout_15.addWidget(self.tableView_Surface)
        self.tabWidget_Res.addTab(self.tab_Surface, "")
        self.tab_Volume = QWidget()
        self.tab_Volume.setObjectName("tab_Volume")
        self.horizontalLayout_4 = QHBoxLayout(self.tab_Volume)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableView_Volume = QTableView(self.tab_Volume)
        self.tableView_Volume.setObjectName("tableView_Volume")
        self.horizontalLayout_4.addWidget(self.tableView_Volume)
        self.tabWidget_Res.addTab(self.tab_Volume, "")
        self.tab_contaceSurface = QWidget()
        self.tab_contaceSurface.setObjectName("tab_contaceSurface")
        self.horizontalLayout = QHBoxLayout(self.tab_contaceSurface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView_contactSurface = QTableView(self.tab_contaceSurface)
        self.tableView_contactSurface.setObjectName("tableView_contactSurface")
        self.horizontalLayout.addWidget(self.tableView_contactSurface)
        self.tabWidget_Res.addTab(self.tab_contaceSurface, "")
        self.tab_3dview = QWidget()
        self.tab_3dview.setObjectName("tab_3dview")
        self.horizontalLayout_6 = QHBoxLayout(self.tab_3dview)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Layout_3dview = QGridLayout()
        self.Layout_3dview.setObjectName("Layout_3dview")
        self.horizontalLayout_3.addLayout(self.Layout_3dview)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.Layout_slider = QVBoxLayout()
        self.Layout_slider.setObjectName("Layout_slider")
        self.Label_idx = QLabel(self.tab_3dview)
        self.Label_idx.setMinimumSize(QSize(0, 0))
        self.Label_idx.setMaximumSize(QSize(16777215, 25))
        self.Label_idx.setText("")
        self.Label_idx.setObjectName("Label_idx")
        self.Layout_slider.addWidget(self.Label_idx)
        self.Slider_3d = QScrollBar(self.tab_3dview)
        self.Slider_3d.setOrientation(Qt.Vertical)
        self.Slider_3d.setObjectName("Slider_3d")
        self.Layout_slider.addWidget(self.Slider_3d)
        self.horizontalLayout_6.addLayout(self.Layout_slider)
        self.tabWidget_Res.addTab(self.tab_3dview, "")
        self.Layout_Result.addWidget(self.tabWidget_Res)
        self.verticalLayout_13.addLayout(self.Layout_Result)
        self.Function.addTab(self.Result, "")

        # ===== Train
        self.Train = QWidget()
        self.Train.setEnabled(True)
        self.Train.setObjectName("Train")
        self.horizontalLayout_5 = QHBoxLayout(self.Train)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Layout_Train = QVBoxLayout()
        self.Layout_Train.setObjectName("Layout_Train")
        self.Layout_title_Tra = QVBoxLayout()
        self.Layout_title_Tra.setObjectName("Layout_title_Tra")
        self.label_title_Tra = QLabel(self.Train)
        self.label_title_Tra.setMaximumSize(QSize(16777215, 50))
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title_Tra.setFont(font)
        self.label_title_Tra.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_title_Tra.setAlignment(Qt.AlignCenter)
        self.label_title_Tra.setObjectName("label_title_Tra")
        self.Layout_title_Tra.addWidget(self.label_title_Tra)
        self.Layout_Train.addLayout(self.Layout_title_Tra)
        self.Layout_params_Train = QGridLayout()
        self.Layout_params_Train.setObjectName("Layout_params_Train")

        self.label_dataFolder_Tra = QLabel(self.Train)
        self.label_dataFolder_Tra.setObjectName("label_dataFolder_Tra")
        self.Layout_params_Train.addWidget(self.label_dataFolder_Tra, 0, 0, 1, 1)
        self.LE_dataFolder_Tra = QLineEdit(self.Train)
        self.LE_dataFolder_Tra.setObjectName("LE_dataFolder_Tra")
        self.Layout_params_Train.addWidget(self.LE_dataFolder_Tra, 0, 1, 1, 1)
        self.Btn_dataFolder_Tra = QPushButton(self.Train)
        self.Btn_dataFolder_Tra.setObjectName("Btn_dataFolder_Tra")
        self.Layout_params_Train.addWidget(self.Btn_dataFolder_Tra, 0, 2, 1, 1)
        self.label_dataName_Tra = QLabel(self.Train)
        self.label_dataName_Tra.setObjectName("label_dataName_Tra")
        self.Layout_params_Train.addWidget(self.label_dataName_Tra, 1, 0, 1, 1)
        self.label_batchSize_Tra = QLabel(self.Train)
        self.label_batchSize_Tra.setObjectName("label_batchSize_Tra")
        self.Layout_params_Train.addWidget(self.label_batchSize_Tra, 2, 0, 1, 1)
        self.LE_batchSize_Tra = QLineEdit(self.Train)
        self.LE_batchSize_Tra.setObjectName("LE_batchSize_Tra")
        self.Layout_params_Train.addWidget(self.LE_batchSize_Tra, 2, 1, 1, 1)

        self.label_netName_Tra = QLabel(self.Train)
        self.label_netName_Tra.setObjectName("label_netName_Tra")
        self.Layout_params_Train.addWidget(self.label_netName_Tra, 3, 0, 1, 1)
        # self.model_lists = QComboBox(self.Segmentation)
        # self.model_lists.setObjectName("CB_model_list")
        # self.model_lists.addItem("")
        # self.model_lists.addItem("")
        # self.Layout_params_Seg.addWidget(self.model_lists, 5, 1, 1, 1)
        self.model_name_tra_lists = QComboBox(self.Train)
        self.model_name_tra_lists.setObjectName("train_model_list")
        self.model_name_tra_lists.addItem("")
        self.model_name_tra_lists.addItem("")
        self.Layout_params_Train.addWidget(self.model_name_tra_lists, 3, 1, 1, 1)
        self.Btn_runTrain = QPushButton(self.Train)
        self.Btn_runTrain.setObjectName("Btn_runTrain")
        self.Layout_params_Train.addWidget(self.Btn_runTrain, 3, 3, 1, 1)

        self.label_modelName_Tra = QLabel(self.Train)
        self.label_modelName_Tra.setObjectName("label_modelName_Tra")
        self.Layout_params_Train.addWidget(self.label_modelName_Tra, 4, 0, 1, 1)
        self.LE_modelName_Tra = QLineEdit(self.Train)
        self.LE_modelName_Tra.setObjectName("LE_modelName_Tra")
        self.Layout_params_Train.addWidget(self.LE_modelName_Tra, 4, 1, 1, 1)
        self.Btn_stopTrain = QPushButton(self.Train)
        self.Btn_stopTrain.setObjectName("Btn_stopTrain")
        self.Layout_params_Train.addWidget(self.Btn_stopTrain, 4, 3, 1, 1)

        self.label_saveFolder_Tra = QLabel(self.Train)
        self.label_saveFolder_Tra.setObjectName("label_saveFolder_Tra")
        self.Layout_params_Train.addWidget(self.label_saveFolder_Tra, 5, 0, 1, 1)
        self.LE_saveFolder_Tra = QLineEdit(self.Train)
        self.LE_saveFolder_Tra.setObjectName("LE_saveFolder_Tra")
        self.Layout_params_Train.addWidget(self.LE_saveFolder_Tra, 5, 1, 1, 1)
        self.Btn_saveFolder_Tra = QPushButton(self.Train)
        self.Btn_saveFolder_Tra.setObjectName("Btn_saveFolder_Tra")
        self.Layout_params_Train.addWidget(self.Btn_saveFolder_Tra, 5, 2, 1, 1)


        # self.label_unusedfirst_Tra = QLabel(self.Train)
        # self.label_unusedfirst_Tra.setText("")
        # self.label_unusedfirst_Tra.setObjectName("label_unusedfirst_Tra")
        # self.Layout_params_Train.addWidget(self.label_unusedfirst_Tra, 5, 0, 1, 1)
        self.label_unusedsecond_Tra = QLabel(self.Train)
        self.label_unusedsecond_Tra.setText("")
        self.label_unusedsecond_Tra.setObjectName("label_unusedsecond_Tra")
        self.Layout_params_Train.addWidget(self.label_unusedsecond_Tra, 6, 0, 1, 1)
        self.label_unusedthird_Tra = QLabel(self.Train)
        self.label_unusedthird_Tra.setText("")
        self.label_unusedthird_Tra.setObjectName("label_unusedthird_Tra")
        self.Layout_params_Train.addWidget(self.label_unusedthird_Tra, 7, 0, 1, 1)
        self.label_unusedforth_Tra = QLabel(self.Train)
        self.label_unusedforth_Tra.setText("")
        self.label_unusedforth_Tra.setObjectName("label_unusedforth_Tra")
        self.Layout_params_Train.addWidget(self.label_unusedforth_Tra, 8, 0, 1, 1)
        self.label_unusedfifth_Tra = QLabel(self.Train)
        self.label_unusedfifth_Tra.setText("")
        self.label_unusedfifth_Tra.setObjectName("label_unusedfifth_Tra")
        self.Layout_params_Train.addWidget(self.label_unusedfifth_Tra, 9, 0, 1, 1)
        self.Layout_Train.addLayout(self.Layout_params_Train)
        self.Layout_progress_Tra = QHBoxLayout()
        self.Layout_progress_Tra.setObjectName("Layout_progress_Tra")
        self.progressTrain = QLabel(self.Train)
        self.progressTrain.setText("")
        self.progressTrain.setObjectName("progressTrain")
        self.Layout_progress_Tra.addWidget(self.progressTrain)
        self.TrainBar = QProgressBar(self.Train)
        self.TrainBar.setMaximumSize(QSize(250, 16777215))
        self.TrainBar.setProperty("value", 0)
        self.TrainBar.setObjectName("TrainBar")
        self.Layout_progress_Tra.addWidget(self.TrainBar)
        self.Layout_Train.addLayout(self.Layout_progress_Tra)
        self.horizontalLayout_5.addLayout(self.Layout_Train)
        self.Function.addTab(self.Train, "")
        self.gridLayout.addWidget(self.Function, 0, 0, 1, 1)
        self.Layout_infomation = QVBoxLayout()
        self.Layout_infomation.setObjectName("Layout_infomation")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.Layout_infomation.addWidget(self.textEdit)
        self.gridLayout.addLayout(self.Layout_infomation, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 699, 23))
        self.menubar.setMouseTracking(True)
        self.menubar.setTabletTracking(True)
        self.menubar.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.menubar.setLayoutDirection(Qt.LeftToRight)
        self.menubar.setAutoFillBackground(True)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setMouseTracking(True)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRun = QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCopy_Right = QAction(MainWindow)
        self.actionCopy_Right.setObjectName("actionCopy_Right")
        self.actionVersion = QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRun_Preprocess = QAction(MainWindow)
        self.actionRun_Preprocess.setObjectName("actionRun_Preprocess")
        self.actionRun_Segmentation = QAction(MainWindow)
        self.actionRun_Segmentation.setObjectName("actionRun_Segmentation")
        self.actionRun_Analysis = QAction(MainWindow)
        self.actionRun_Analysis.setObjectName("actionRun_Analysis")
        self.actionRun_ALL = QAction(MainWindow)
        self.actionRun_ALL.setObjectName("actionRun_ALL")
        self.actionOpen_Result_Folder = QAction(MainWindow)
        self.actionOpen_Result_Folder.setObjectName("actionOpen_Result_Folder")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionNew_Project = QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionSave_Project = QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionLoad_Project = QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionLicense = QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionLoad_Project)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuRun.addAction(self.actionRun_Preprocess)
        self.menuRun.addAction(self.actionRun_Segmentation)
        self.menuRun.addAction(self.actionRun_Analysis)
        self.menuRun.addAction(self.actionRun_ALL)
        self.menuRun.addAction(self.actionOpen_Result_Folder)
        self.menuAbout.addAction(self.actionVersion)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionLicense)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.Function.setCurrentIndex(0)
        self.tabWidget_Res.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LE_rawFolder, self.Btn_rawFolder)
        MainWindow.setTabOrder(self.Btn_rawFolder, self.CB_embryoNames)
        MainWindow.setTabOrder(self.CB_embryoNames, self.LE_xyResolution)
        MainWindow.setTabOrder(self.LE_xyResolution, self.LE_zResolution)
        MainWindow.setTabOrder(self.LE_zResolution, self.LE_reduceRatio)
        MainWindow.setTabOrder(self.LE_reduceRatio, self.LE_sliceNum)
        MainWindow.setTabOrder(self.LE_sliceNum, self.LE_maxTime)
        MainWindow.setTabOrder(self.LE_maxTime, self.LE_projectFolder)
        MainWindow.setTabOrder(self.LE_projectFolder, self.Btn_projectFolder)
        MainWindow.setTabOrder(self.Btn_projectFolder, self.LE_lineage)
        MainWindow.setTabOrder(self.LE_lineage, self.Btn_lineageFile)
        MainWindow.setTabOrder(self.Btn_lineageFile, self.LE_numberDict)
        MainWindow.setTabOrder(self.LE_numberDict, self.Btn_numberDict)
        MainWindow.setTabOrder(self.Btn_numberDict, self.Btn_runPreprocess)
        MainWindow.setTabOrder(self.Btn_runPreprocess, self.Btn_stopPreprocess)
        MainWindow.setTabOrder(self.Btn_stopPreprocess, self.LE_projectFolder_Seg)
        MainWindow.setTabOrder(self.LE_projectFolder_Seg, self.Btn_projectFolder_Seg)
        MainWindow.setTabOrder(self.Btn_projectFolder_Seg, self.CB_embryoNames_Seg)
        MainWindow.setTabOrder(self.CB_embryoNames_Seg, self.LE_maxTime_Seg)
        MainWindow.setTabOrder(self.LE_maxTime_Seg, self.LE_batchSize_Seg)
        MainWindow.setTabOrder(self.LE_batchSize_Seg, self.label_model_tag)
        MainWindow.setTabOrder(self.label_model_tag, self.CB_lineage_Seg)
        MainWindow.setTabOrder(self.CB_lineage_Seg, self.LE_modelFile_Seg)
        MainWindow.setTabOrder(self.LE_modelFile_Seg, self.Btn_modelFile_Seg)
        MainWindow.setTabOrder(self.Btn_modelFile_Seg, self.Btn_runSegmentation)
        MainWindow.setTabOrder(self.Btn_runSegmentation, self.Btn_stopSegmentation)
        MainWindow.setTabOrder(self.Btn_stopSegmentation, self.LE_sliceNum_Ana)
        MainWindow.setTabOrder(self.LE_sliceNum_Ana, self.LE_xyResolution_Ana)
        MainWindow.setTabOrder(self.LE_xyResolution_Ana, self.LE_numberDict_Ana)
        MainWindow.setTabOrder(self.LE_numberDict_Ana, self.Btn_numberDict_Ana)
        MainWindow.setTabOrder(self.Btn_numberDict_Ana, self.LE_rawFolder_Ana)
        MainWindow.setTabOrder(self.LE_rawFolder_Ana, self.Btn_rawFolder_Ana)
        MainWindow.setTabOrder(self.Btn_rawFolder_Ana, self.CB_embryoNames_Ana)
        MainWindow.setTabOrder(self.CB_embryoNames_Ana, self.LE_projectFolder_Ana)
        MainWindow.setTabOrder(self.LE_projectFolder_Ana, self.Btn_projectFolder_Ana)
        MainWindow.setTabOrder(self.Btn_projectFolder_Ana, self.LE_lineage_Ana)
        MainWindow.setTabOrder(self.LE_lineage_Ana, self.Btn_lineageFile_Ana)
        MainWindow.setTabOrder(self.Btn_lineageFile_Ana, self.Btn_runAnalysis)
        MainWindow.setTabOrder(self.Btn_runAnalysis, self.Btn_stopAnalysis)
        # MainWindow.setTabOrder(self.Btn_stopAnalysis, self.Btn_runAll)
        # MainWindow.setTabOrder(self.Btn_runAll, self.tableView_Surface)
        MainWindow.setTabOrder(self.tableView_Surface, self.tableView_Volume)
        MainWindow.setTabOrder(self.tableView_Volume, self.LE_dataFolder_Tra)
        MainWindow.setTabOrder(self.LE_dataFolder_Tra, self.Btn_dataFolder_Tra)
        MainWindow.setTabOrder(self.Btn_dataFolder_Tra, self.LE_batchSize_Tra)
        MainWindow.setTabOrder(self.LE_batchSize_Tra, self.LE_modelName_Tra)
        MainWindow.setTabOrder(self.LE_modelName_Tra, self.LE_saveFolder_Tra)
        MainWindow.setTabOrder(self.LE_saveFolder_Tra, self.Btn_saveFolder_Tra)
        MainWindow.setTabOrder(self.Btn_saveFolder_Tra, self.Btn_runTrain)
        MainWindow.setTabOrder(self.Btn_runTrain, self.Btn_stopTrain)
        MainWindow.setTabOrder(self.Btn_stopTrain, self.Function)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CShaperApp"))
        self.label_title_Pre.setText(_translate("MainWindow", "Experimental Information"))
        self.label_projectFolder_Pre.setText(_translate("MainWindow", "Project Folder:"))
        self.label_rawFolder_Pre.setText(_translate("MainWindow", "Raw Folder:"))
        self.label_zReso_Pre.setText(_translate("MainWindow", "Z Resolution:"))
        self.Btn_numberDict.setText(_translate("MainWindow", "Choose"))
        self.Btn_rawFolder.setText(_translate("MainWindow", "Choose"))
        self.Btn_projectFolder.setText(_translate("MainWindow", "Choose"))
        self.label_reduceRatio_Pre.setText(_translate("MainWindow", "Reduce Ratio:"))
        self.label_sliceNum_Pre.setText(_translate("MainWindow", "Slice Num:"))
        self.Btn_lineageFile.setText(_translate("MainWindow", "Choose"))
        self.label_xyum_Pre.setText(_translate("MainWindow", "um"))
        self.label_maxTime_Pre.setText(_translate("MainWindow", "Max Time:"))
        self.label_numberDict_Pre.setText(_translate("MainWindow", "Number Dictionary:"))
        self.label_embryoName_Pre.setText(_translate("MainWindow", "Embryo Name:"))
        self.label_lineageFile_Pre.setText(_translate("MainWindow", "Lineage File:"))
        self.label_zum_Pre.setText(_translate("MainWindow", "um"))
        self.Btn_runPreprocess.setText(_translate("MainWindow", "Run Preprocess"))
        self.label_xyReso_Pre.setText(_translate("MainWindow", "X-Y Resolution:   "))
        self.Btn_stopPreprocess.setText(_translate("MainWindow", "Stop Preprocess "))
        self.Function.setTabText(self.Function.indexOf(self.Preprocess), _translate("MainWindow", "Preprocess"))
        self.label_title_Seg.setText(_translate("MainWindow", "Segmentation Parameters"))
        self.Btn_stopSegmentation.setText(_translate("MainWindow", "Stop Segmentation"))
        # Select lineage
        self.CB_lineage_Seg.setItemText(0, _translate("MainWindow", "No lineage"))
        self.CB_lineage_Seg.setItemText(1, _translate("MainWindow", "Before segmentation"))
        self.CB_lineage_Seg.setItemText(2, _translate("MainWindow", "After segmentation"))

        self.model_lists.setItemText(0, _translate("MainWindow", "CShaper"))
        self.model_lists.setItemText(1, _translate("MainWindow", "CMap"))
        self.model_name_tra_lists.setItemText(0, _translate("MainWindow", "CShaper"))
        self.model_name_tra_lists.setItemText(1, _translate("MainWindow", "CMap"))

        self.Btn_runSegmentation.setText(_translate("MainWindow", "Run Segmentation"))
        self.label_projectFolder_Seg.setText(_translate("MainWindow", "Project Folder:   "))
        self.label_embryoName_Seg.setText(_translate("MainWindow", "Embryo Names:"))
        self.label_modelFile_Seg.setText(_translate("MainWindow", "Model File:"))
        self.label_batchSize_Seg.setText(_translate("MainWindow", "Batch Size:"))
        self.Btn_projectFolder_Seg.setText(_translate("MainWindow", "Choose"))
        self.label_maxTime_Seg.setText(_translate("MainWindow", "Max Time:"))
        self.Btn_modelFile_Seg.setText(_translate("MainWindow", "Choose"))
        self.label_lineage_Seg.setText(_translate("MainWindow", "Use Lineage?"))
        self.label_model_tag.setText(_translate("MainWindow", "Which model?"))
        self.Function.setTabText(self.Function.indexOf(self.Segmentation), _translate("MainWindow", "Segmentation"))
        self.label_title_Ana.setText(_translate("MainWindow", "Analysis Parameters"))
        self.Btn_lineageFile_Ana.setText(_translate("MainWindow", "Choose"))
        self.Btn_stopAnalysis.setText(_translate("MainWindow", "Stop Analysis"))
        self.Btn_rawFolder_Ana.setText(_translate("MainWindow", "Choose"))
        self.label_rawFolder_Ana.setText(_translate("MainWindow", "Raw Folder:"))
        self.Btn_numberDict_Ana.setText(_translate("MainWindow", "Choose"))
        # self.Btn_runAll.setText(_translate("MainWindow", "Run Preprocess, \n"
# "Segmentation and Analysis"))
        self.label_numberDict_Ana.setText(_translate("MainWindow", "Number Dictionary:"))
        self.label_sliceNum_Ana.setText(_translate("MainWindow", "Slice Num:"))
        self.label_lineageFile_Ana.setText(_translate("MainWindow", "Lineage File:"))
        self.label_projectFolder_Ana.setText(_translate("MainWindow", "Project Folder:"))
        self.label_embryoName_Ana.setText(_translate("MainWindow", "Embryo Names:"))
        self.Btn_runAnalysis.setText(_translate("MainWindow", "Run Analysis"))
        self.label_xyReso_Ana.setText(_translate("MainWindow", "X-Y Resolution:"))
        self.Btn_projectFolder_Ana.setText(_translate("MainWindow", "Choose"))
        self.Function.setTabText(self.Function.indexOf(self.Analysis), _translate("MainWindow", "Analysis"))
        self.label_title_Res.setText(_translate("MainWindow", "Show Results"))
        self.tabWidget_Res.setTabText(self.tabWidget_Res.indexOf(self.tab_Surface), _translate("MainWindow", "Surface"))
        self.tabWidget_Res.setTabText(self.tabWidget_Res.indexOf(self.tab_Volume), _translate("MainWindow", "Volume"))
        self.tabWidget_Res.setTabText(self.tabWidget_Res.indexOf(self.tab_contaceSurface), _translate("MainWindow", "Contact Surface"))
        self.tabWidget_Res.setTabText(self.tabWidget_Res.indexOf(self.tab_3dview), _translate("MainWindow", "! 3D View"))
        self.Function.setTabText(self.Function.indexOf(self.Result), _translate("MainWindow", "Result"))
        self.label_title_Tra.setText(_translate("MainWindow", "Train New Model"))
        self.Btn_saveFolder_Tra.setText(_translate("MainWindow", "Choose"))
        self.label_modelName_Tra.setText(_translate("MainWindow", "Save Name: "))
        self.label_saveFolder_Tra.setText(_translate("MainWindow", "Save Folder: "))
        self.Btn_dataFolder_Tra.setText(_translate("MainWindow", "Choose"))
        self.label_batchSize_Tra.setText(_translate("MainWindow", "Batch Size: "))
        self.label_dataName_Tra.setText(_translate("MainWindow", "Data Names: "))
        self.label_netName_Tra.setText(_translate("MainWindow", "Model Name: "))
        self.Btn_runTrain.setText(_translate("MainWindow", "Run Train"))
        self.Btn_stopTrain.setText(_translate("MainWindow", "Stop Train"))
        self.label_dataFolder_Tra.setText(_translate("MainWindow", "Data Folder:"))
        self.Function.setTabText(self.Function.indexOf(self.Train), _translate("MainWindow", "Train"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuRun.setTitle(_translate("MainWindow", "&Run"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionCopy_Right.setText(_translate("MainWindow", "Copy Right"))
        self.actionVersion.setText(_translate("MainWindow", "Online Document"))
        self.actionHelp.setText(_translate("MainWindow", "About CShaperApp"))
        self.actionRun_Preprocess.setText(_translate("MainWindow", "Run Preprocess"))
        self.actionRun_Segmentation.setText(_translate("MainWindow", "Run Segmentation"))
        self.actionRun_Analysis.setText(_translate("MainWindow", "Run Analysis"))
        self.actionRun_ALL.setText(_translate("MainWindow", "Run All"))
        self.actionOpen_Result_Folder.setText(_translate("MainWindow", "Open Result Folder"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project"))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project"))
        self.actionLicense.setText(_translate("MainWindow", "License"))

